#!/bin/bash



# Install Nginx
sudo apt install nginx -y

# Start Nginx service and check its status
sudo systemctl start nginx
sudo systemctl status nginx

# Remove existing files in the Nginx web root
sudo rm -rf /var/www/html/*

# Navigate to the web root directory
cd /var/www/html || exit

# Create a new index.html file with custom content for Nginx
FILE="index.html"
cat <<EOL > $FILE
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 20px;
        }
        h1 {
            color: #333;
        }
        p {
            color: #555;
        }
    </style>
</head>
<body>
    <h1>Welcome to the Index Page Macarious</h1>
    <p>This is a simple index page generated by a Bash script.</p>
</body>
</html>
EOL

# Reload Nginx to serve the new index page
sudo systemctl reload nginx

# Final message
echo "Script execution completed. Apache is running on port 8080 and Nginx is serving the new index page."
